module.exports = {
  USERNAMES_RECIEVED: "USERNAMES_RECIEVED",
  SESSION_RECIEVED: "SESSION_RECIEVED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  RENDER_SIGNUP_MODAL: "RENDER_SIGNUP_MODAL",
  RENDER_LOGIN_MODAL: "RENDER_LOGIN_MODAL",
  RENDER_MESSENGER: "RENDER_MESSENGER",
  RENDER_OPAQUE_NAV_BAR: "RENDER_OPAQUE_NAV_BAR",
  RENDER_TRANSPARENT_NAV_BAR: "RENDER_TRANSPARENT_NAV_BAR",
  CLOSE_MODALS: "CLOSE_MODALS",
  INVALID_ENTRY: "INVALID_ENTRY"
}
