module.exports = {
  USERS_RECIEVED: "USERS_RECIEVED",
  SESSION_RECIEVED: "SESSION_RECIEVED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  RENDER_SIGNUP_MODAL: "RENDER_SIGNUP_MODAL",
  RENDER_LOGIN_MODAL: "RENDER_LOGIN_MODAL",
  INVALID_ENTRY: "INVALID_ENTRY"
}
